module.exports = {
  NEW_PHOTO: "NEW_PHOTO",
  CURRENT_USER_PHOTOS: "CURRENT_USER_PHOTOS",
  OTHER_USER_DEFAULT_PIC: "OTHER_USER_DEFAULT_PIC",
  OTHER_USER_PHOTOS: "OTHER_USER_PHOTOS",
  UPDATE_DESCRIPTION: "UPDATE_DESCRIPTION",
  REMOVE_PHOTO: "REMOVE_PHOTO",
  SET_NEW_DEFAULT: "SET_NEW_DEFAULT",
};
