module.exports = {
  NEW_PHOTO: 'NEW_PHOTO',
  CURRENT_USER_PHOTOS: 'CURRENT_USER_PHOTOS',
  OTHER_USER_DEFAULT_PIC: 'OTHER_USER_DEFAULT_PIC',
  OTHER_USER_PHOTOS: 'OTHER_USER_PHOTOS',
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION'
};
