module.exports = {
  LOG_OUT: "LOG_OUT",
  LOG_IN: "LOG_IN",
  ADD_USER_TO_LIKES: 'ADD_USER_TO_LIKES',
  REMOVE_USER_FROM_LIKES: 'REMOVE_USER_FROM_LIKES',
  ADD_NEW_ANSWER_TO_USER: 'ADD_NEW_ANSWER_TO_USER'
};
